# Generated by Django 5.2.17 on 2026-09-19 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_order_id', models.CharField(max_length=100, unique=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('shop', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('total', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('simple_name', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('packing', models.CharField(max_length=150)),
                ('unit', models.CharField(default='case', max_length=50)),
                ('rate', models.BigIntegerField()),
                ('mrp', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company', 'brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_snapshot', models.UUIDField()),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.BigIntegerField()),
                ('line_total', models.BigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.order')),
            ],
        ),
    ]
