# Generated by Django 5.2.17 on 2026-09-19 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_invoice_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_number', models.CharField(max_length=50, unique=True)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=100)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('taxable_total', models.BigIntegerField(default=0)),
                ('gst_total', models.BigIntegerField(default=0)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tds_total', models.BigIntegerField(default=0)),
                ('grand_total', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('tds_section', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.BigIntegerField()),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalogue.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('taxable_total', models.BigIntegerField(default=0)),
                ('gst_total', models.BigIntegerField(default=0)),
                ('grand_total', models.BigIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='catalogue.purchase')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='catalogue.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.BigIntegerField()),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.purchasereturn')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('taxable_total', models.BigIntegerField(default=0)),
                ('gst_total', models.BigIntegerField(default=0)),
                ('grand_total', models.BigIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='catalogue.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='catalogue.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.BigIntegerField()),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.salesreturn')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalogue.supplier'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Opening'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('sales_return', 'Sales return'), ('purchase_return', 'Purchase return'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.BigIntegerField(default=0)),
                ('reference_type', models.CharField(blank=True, max_length=30)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalogue.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalogue.warehouse')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalogue.warehouse'),
        ),
    ]
