# Generated by Django 5.2.17 on 2026-09-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_purchase_supplier_warehouse_purchaseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
