# Generated by Django 5.2.17 on 2026-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_hsn_product_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
