# Generated by Django 5.2.17 on 2026-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_order_seller_snapshot_purchase_supplier_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='product_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='product_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
