# Generated by Django 5.2.17 on 2026-09-22 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_purchasereturn_source_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='scheme_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='scheme_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Trade scheme shown to shops, e.g. 10 for 10% off. Applied on the Marg bill.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
